// Code generated by protoc-gen-go. DO NOT EDIT.
// source: electricmeter.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ElectricMeterUpdateRequest struct {
	Devid                string   `protobuf:"bytes,1,opt,name=devid,proto3" json:"devid,omitempty"`
	Devtype              string   `protobuf:"bytes,2,opt,name=devtype,proto3" json:"devtype,omitempty"`
	Devaddr              string   `protobuf:"bytes,3,opt,name=devaddr,proto3" json:"devaddr,omitempty"`
	Commif               string   `protobuf:"bytes,4,opt,name=commif,proto3" json:"commif,omitempty"`
	Dname                string   `protobuf:"bytes,5,opt,name=dname,proto3" json:"dname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElectricMeterUpdateRequest) Reset()         { *m = ElectricMeterUpdateRequest{} }
func (m *ElectricMeterUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ElectricMeterUpdateRequest) ProtoMessage()    {}
func (*ElectricMeterUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_electricmeter_012f7eda0fea4bd3, []int{0}
}
func (m *ElectricMeterUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectricMeterUpdateRequest.Unmarshal(m, b)
}
func (m *ElectricMeterUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectricMeterUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *ElectricMeterUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectricMeterUpdateRequest.Merge(dst, src)
}
func (m *ElectricMeterUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ElectricMeterUpdateRequest.Size(m)
}
func (m *ElectricMeterUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectricMeterUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ElectricMeterUpdateRequest proto.InternalMessageInfo

func (m *ElectricMeterUpdateRequest) GetDevid() string {
	if m != nil {
		return m.Devid
	}
	return ""
}

func (m *ElectricMeterUpdateRequest) GetDevtype() string {
	if m != nil {
		return m.Devtype
	}
	return ""
}

func (m *ElectricMeterUpdateRequest) GetDevaddr() string {
	if m != nil {
		return m.Devaddr
	}
	return ""
}

func (m *ElectricMeterUpdateRequest) GetCommif() string {
	if m != nil {
		return m.Commif
	}
	return ""
}

func (m *ElectricMeterUpdateRequest) GetDname() string {
	if m != nil {
		return m.Dname
	}
	return ""
}

type ElectricMeterUpdateResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElectricMeterUpdateResponse) Reset()         { *m = ElectricMeterUpdateResponse{} }
func (m *ElectricMeterUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ElectricMeterUpdateResponse) ProtoMessage()    {}
func (*ElectricMeterUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_electricmeter_012f7eda0fea4bd3, []int{1}
}
func (m *ElectricMeterUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectricMeterUpdateResponse.Unmarshal(m, b)
}
func (m *ElectricMeterUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectricMeterUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *ElectricMeterUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectricMeterUpdateResponse.Merge(dst, src)
}
func (m *ElectricMeterUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ElectricMeterUpdateResponse.Size(m)
}
func (m *ElectricMeterUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectricMeterUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ElectricMeterUpdateResponse proto.InternalMessageInfo

func (m *ElectricMeterUpdateResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ElectricMeterUpdateRequest)(nil), "api.ElectricMeterUpdateRequest")
	proto.RegisterType((*ElectricMeterUpdateResponse)(nil), "api.ElectricMeterUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ElectricMeterClient is the client API for ElectricMeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ElectricMeterClient interface {
	// 添加或更新电表设备
	ElectricMeterUpdate(ctx context.Context, in *ElectricMeterUpdateRequest, opts ...grpc.CallOption) (*ElectricMeterUpdateResponse, error)
}

type electricMeterClient struct {
	cc *grpc.ClientConn
}

func NewElectricMeterClient(cc *grpc.ClientConn) ElectricMeterClient {
	return &electricMeterClient{cc}
}

func (c *electricMeterClient) ElectricMeterUpdate(ctx context.Context, in *ElectricMeterUpdateRequest, opts ...grpc.CallOption) (*ElectricMeterUpdateResponse, error) {
	out := new(ElectricMeterUpdateResponse)
	err := c.cc.Invoke(ctx, "/api.ElectricMeter/ElectricMeterUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElectricMeterServer is the server API for ElectricMeter service.
type ElectricMeterServer interface {
	// 添加或更新电表设备
	ElectricMeterUpdate(context.Context, *ElectricMeterUpdateRequest) (*ElectricMeterUpdateResponse, error)
}

func RegisterElectricMeterServer(s *grpc.Server, srv ElectricMeterServer) {
	s.RegisterService(&_ElectricMeter_serviceDesc, srv)
}

func _ElectricMeter_ElectricMeterUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectricMeterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectricMeterServer).ElectricMeterUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ElectricMeter/ElectricMeterUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectricMeterServer).ElectricMeterUpdate(ctx, req.(*ElectricMeterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ElectricMeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ElectricMeter",
	HandlerType: (*ElectricMeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ElectricMeterUpdate",
			Handler:    _ElectricMeter_ElectricMeterUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "electricmeter.proto",
}

func init() { proto.RegisterFile("electricmeter.proto", fileDescriptor_electricmeter_012f7eda0fea4bd3) }

var fileDescriptor_electricmeter_012f7eda0fea4bd3 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0x9d, 0x77, 0x62, 0xc0, 0x26, 0x27, 0x12, 0x57, 0xd1, 0x63, 0xb1, 0x10, 0x8b,
	0x3d, 0x50, 0x6c, 0xec, 0x2d, 0x6d, 0x16, 0xac, 0x97, 0xb8, 0x19, 0x8f, 0xc0, 0x6e, 0x26, 0x26,
	0xb3, 0x07, 0x36, 0x16, 0xbe, 0x80, 0x85, 0xbe, 0x99, 0xaf, 0xe0, 0x83, 0xc8, 0x66, 0xa3, 0x20,
	0xdc, 0x96, 0x5f, 0xe6, 0xff, 0x67, 0xfe, 0xfc, 0x7c, 0x01, 0x0d, 0xd4, 0xe4, 0x4d, 0xdd, 0x02,
	0x81, 0x2f, 0x9c, 0x47, 0x42, 0x31, 0x55, 0xce, 0x64, 0x27, 0x6b, 0xc4, 0x75, 0x03, 0x2b, 0xe5,
	0xcc, 0x4a, 0x59, 0x8b, 0xa4, 0xc8, 0xa0, 0x0d, 0x83, 0x24, 0xff, 0x64, 0x3c, 0xbb, 0x4b, 0xd6,
	0xfb, 0xde, 0xfa, 0xe0, 0xb4, 0x22, 0x28, 0xe1, 0xb9, 0x83, 0x40, 0xe2, 0x80, 0xcf, 0x34, 0x6c,
	0x8c, 0x96, 0x6c, 0xc9, 0x2e, 0xf6, 0xca, 0x01, 0x84, 0xe4, 0xbb, 0x1a, 0x36, 0xf4, 0xe2, 0x40,
	0x4e, 0xe2, 0xfb, 0x2f, 0xa6, 0x89, 0xd2, 0xda, 0xcb, 0xe9, 0xdf, 0xa4, 0x47, 0x71, 0xc8, 0xe7,
	0x35, 0xb6, 0xad, 0x79, 0x92, 0x3b, 0x71, 0x90, 0x28, 0x5e, 0xb0, 0xaa, 0x05, 0x39, 0x4b, 0x17,
	0x7a, 0xc8, 0x6f, 0xf8, 0xf1, 0xd6, 0x54, 0xc1, 0xa1, 0x0d, 0xd0, 0x2f, 0x2b, 0x21, 0x74, 0x0d,
	0xa5, 0x5c, 0x89, 0xae, 0xde, 0x19, 0xdf, 0xff, 0xe7, 0x13, 0xaf, 0x7c, 0xb1, 0x65, 0x91, 0x38,
	0x2b, 0x94, 0x33, 0xc5, 0xf8, 0xc7, 0xb3, 0xe5, 0xb8, 0x60, 0xc8, 0x90, 0x9f, 0xbf, 0x7d, 0x7d,
	0x7f, 0x4c, 0x4e, 0xb3, 0xa3, 0xd8, 0x6c, 0xac, 0xbd, 0x52, 0x5a, 0x57, 0xe8, 0xab, 0xce, 0x45,
	0xe9, 0x2d, 0xbb, 0x7c, 0x9c, 0xc7, 0x9a, 0xaf, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x76, 0x6f,
	0x2d, 0xff, 0xa0, 0x01, 0x00, 0x00,
}
