// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetGatewayManageRequest struct {
	// string clientId=1;
	ClientIp             string   `protobuf:"bytes,2,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	Inet                 string   `protobuf:"bytes,8,opt,name=inet,proto3" json:"inet,omitempty"`
	Netmask              string   `protobuf:"bytes,9,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Gateway              string   `protobuf:"bytes,10,opt,name=gateway,proto3" json:"gateway,omitempty"`
	ServerIp             string   `protobuf:"bytes,3,opt,name=serverIp,proto3" json:"serverIp,omitempty"`
	ServerName           string   `protobuf:"bytes,4,opt,name=serverName,proto3" json:"serverName,omitempty"`
	ServerPort           string   `protobuf:"bytes,5,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	MqttUsername         string   `protobuf:"bytes,6,opt,name=mqttUsername,proto3" json:"mqttUsername,omitempty"`
	MqttPassword         string   `protobuf:"bytes,7,opt,name=mqttPassword,proto3" json:"mqttPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGatewayManageRequest) Reset()         { *m = SetGatewayManageRequest{} }
func (m *SetGatewayManageRequest) String() string { return proto.CompactTextString(m) }
func (*SetGatewayManageRequest) ProtoMessage()    {}
func (*SetGatewayManageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{0}
}
func (m *SetGatewayManageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGatewayManageRequest.Unmarshal(m, b)
}
func (m *SetGatewayManageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGatewayManageRequest.Marshal(b, m, deterministic)
}
func (dst *SetGatewayManageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGatewayManageRequest.Merge(dst, src)
}
func (m *SetGatewayManageRequest) XXX_Size() int {
	return xxx_messageInfo_SetGatewayManageRequest.Size(m)
}
func (m *SetGatewayManageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGatewayManageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetGatewayManageRequest proto.InternalMessageInfo

func (m *SetGatewayManageRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *SetGatewayManageRequest) GetInet() string {
	if m != nil {
		return m.Inet
	}
	return ""
}

func (m *SetGatewayManageRequest) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *SetGatewayManageRequest) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *SetGatewayManageRequest) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *SetGatewayManageRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *SetGatewayManageRequest) GetServerPort() string {
	if m != nil {
		return m.ServerPort
	}
	return ""
}

func (m *SetGatewayManageRequest) GetMqttUsername() string {
	if m != nil {
		return m.MqttUsername
	}
	return ""
}

func (m *SetGatewayManageRequest) GetMqttPassword() string {
	if m != nil {
		return m.MqttPassword
	}
	return ""
}

type SetGatewayManageResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGatewayManageResponse) Reset()         { *m = SetGatewayManageResponse{} }
func (m *SetGatewayManageResponse) String() string { return proto.CompactTextString(m) }
func (*SetGatewayManageResponse) ProtoMessage()    {}
func (*SetGatewayManageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{1}
}
func (m *SetGatewayManageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGatewayManageResponse.Unmarshal(m, b)
}
func (m *SetGatewayManageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGatewayManageResponse.Marshal(b, m, deterministic)
}
func (dst *SetGatewayManageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGatewayManageResponse.Merge(dst, src)
}
func (m *SetGatewayManageResponse) XXX_Size() int {
	return xxx_messageInfo_SetGatewayManageResponse.Size(m)
}
func (m *SetGatewayManageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGatewayManageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetGatewayManageResponse proto.InternalMessageInfo

func (m *SetGatewayManageResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetGatewayManageResponse struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientIp             string   `protobuf:"bytes,2,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	Netmask              string   `protobuf:"bytes,10,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Gateway              string   `protobuf:"bytes,11,opt,name=gateway,proto3" json:"gateway,omitempty"`
	ServerIp             string   `protobuf:"bytes,3,opt,name=serverIp,proto3" json:"serverIp,omitempty"`
	ServerName           string   `protobuf:"bytes,4,opt,name=serverName,proto3" json:"serverName,omitempty"`
	ServerPort           string   `protobuf:"bytes,5,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	MqttUsername         string   `protobuf:"bytes,6,opt,name=mqttUsername,proto3" json:"mqttUsername,omitempty"`
	MqttPassword         string   `protobuf:"bytes,7,opt,name=mqttPassword,proto3" json:"mqttPassword,omitempty"`
	Interval             string   `protobuf:"bytes,8,opt,name=interval,proto3" json:"interval,omitempty"`
	MqttStatus           string   `protobuf:"bytes,9,opt,name=mqttStatus,proto3" json:"mqttStatus,omitempty"`
	Historydays          string   `protobuf:"bytes,12,opt,name=historydays,proto3" json:"historydays,omitempty"`
	SystemStat           string   `protobuf:"bytes,13,opt,name=systemStat,proto3" json:"systemStat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayManageResponse) Reset()         { *m = GetGatewayManageResponse{} }
func (m *GetGatewayManageResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayManageResponse) ProtoMessage()    {}
func (*GetGatewayManageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{2}
}
func (m *GetGatewayManageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayManageResponse.Unmarshal(m, b)
}
func (m *GetGatewayManageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayManageResponse.Marshal(b, m, deterministic)
}
func (dst *GetGatewayManageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayManageResponse.Merge(dst, src)
}
func (m *GetGatewayManageResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayManageResponse.Size(m)
}
func (m *GetGatewayManageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayManageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayManageResponse proto.InternalMessageInfo

func (m *GetGatewayManageResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetGatewayManageResponse) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *GetGatewayManageResponse) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *GetGatewayManageResponse) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *GetGatewayManageResponse) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *GetGatewayManageResponse) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *GetGatewayManageResponse) GetServerPort() string {
	if m != nil {
		return m.ServerPort
	}
	return ""
}

func (m *GetGatewayManageResponse) GetMqttUsername() string {
	if m != nil {
		return m.MqttUsername
	}
	return ""
}

func (m *GetGatewayManageResponse) GetMqttPassword() string {
	if m != nil {
		return m.MqttPassword
	}
	return ""
}

func (m *GetGatewayManageResponse) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *GetGatewayManageResponse) GetMqttStatus() string {
	if m != nil {
		return m.MqttStatus
	}
	return ""
}

func (m *GetGatewayManageResponse) GetHistorydays() string {
	if m != nil {
		return m.Historydays
	}
	return ""
}

func (m *GetGatewayManageResponse) GetSystemStat() string {
	if m != nil {
		return m.SystemStat
	}
	return ""
}

type GetGatewayManageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayManageRequest) Reset()         { *m = GetGatewayManageRequest{} }
func (m *GetGatewayManageRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayManageRequest) ProtoMessage()    {}
func (*GetGatewayManageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{3}
}
func (m *GetGatewayManageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayManageRequest.Unmarshal(m, b)
}
func (m *GetGatewayManageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayManageRequest.Marshal(b, m, deterministic)
}
func (dst *GetGatewayManageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayManageRequest.Merge(dst, src)
}
func (m *GetGatewayManageRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayManageRequest.Size(m)
}
func (m *GetGatewayManageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayManageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayManageRequest proto.InternalMessageInfo

type GetSuppotRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuppotRequest) Reset()         { *m = GetSuppotRequest{} }
func (m *GetSuppotRequest) String() string { return proto.CompactTextString(m) }
func (*GetSuppotRequest) ProtoMessage()    {}
func (*GetSuppotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{4}
}
func (m *GetSuppotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuppotRequest.Unmarshal(m, b)
}
func (m *GetSuppotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuppotRequest.Marshal(b, m, deterministic)
}
func (dst *GetSuppotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuppotRequest.Merge(dst, src)
}
func (m *GetSuppotRequest) XXX_Size() int {
	return xxx_messageInfo_GetSuppotRequest.Size(m)
}
func (m *GetSuppotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuppotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuppotRequest proto.InternalMessageInfo

type GetSuppotResponse struct {
	Supportlist          []string `protobuf:"bytes,1,rep,name=supportlist,proto3" json:"supportlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuppotResponse) Reset()         { *m = GetSuppotResponse{} }
func (m *GetSuppotResponse) String() string { return proto.CompactTextString(m) }
func (*GetSuppotResponse) ProtoMessage()    {}
func (*GetSuppotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{5}
}
func (m *GetSuppotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuppotResponse.Unmarshal(m, b)
}
func (m *GetSuppotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuppotResponse.Marshal(b, m, deterministic)
}
func (dst *GetSuppotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuppotResponse.Merge(dst, src)
}
func (m *GetSuppotResponse) XXX_Size() int {
	return xxx_messageInfo_GetSuppotResponse.Size(m)
}
func (m *GetSuppotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuppotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuppotResponse proto.InternalMessageInfo

func (m *GetSuppotResponse) GetSupportlist() []string {
	if m != nil {
		return m.Supportlist
	}
	return nil
}

type SetIntervalRequest struct {
	Interval             int32    `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetIntervalRequest) Reset()         { *m = SetIntervalRequest{} }
func (m *SetIntervalRequest) String() string { return proto.CompactTextString(m) }
func (*SetIntervalRequest) ProtoMessage()    {}
func (*SetIntervalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{6}
}
func (m *SetIntervalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetIntervalRequest.Unmarshal(m, b)
}
func (m *SetIntervalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetIntervalRequest.Marshal(b, m, deterministic)
}
func (dst *SetIntervalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetIntervalRequest.Merge(dst, src)
}
func (m *SetIntervalRequest) XXX_Size() int {
	return xxx_messageInfo_SetIntervalRequest.Size(m)
}
func (m *SetIntervalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetIntervalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetIntervalRequest proto.InternalMessageInfo

func (m *SetIntervalRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type SetIntervalResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetIntervalResponse) Reset()         { *m = SetIntervalResponse{} }
func (m *SetIntervalResponse) String() string { return proto.CompactTextString(m) }
func (*SetIntervalResponse) ProtoMessage()    {}
func (*SetIntervalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{7}
}
func (m *SetIntervalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetIntervalResponse.Unmarshal(m, b)
}
func (m *SetIntervalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetIntervalResponse.Marshal(b, m, deterministic)
}
func (dst *SetIntervalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetIntervalResponse.Merge(dst, src)
}
func (m *SetIntervalResponse) XXX_Size() int {
	return xxx_messageInfo_SetIntervalResponse.Size(m)
}
func (m *SetIntervalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetIntervalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetIntervalResponse proto.InternalMessageInfo

func (m *SetIntervalResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SetTLSConfigRequest struct {
	Cafile               string   `protobuf:"bytes,1,opt,name=cafile,proto3" json:"cafile,omitempty"`
	Certfile             string   `protobuf:"bytes,2,opt,name=certfile,proto3" json:"certfile,omitempty"`
	Keyfile              string   `protobuf:"bytes,3,opt,name=keyfile,proto3" json:"keyfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTLSConfigRequest) Reset()         { *m = SetTLSConfigRequest{} }
func (m *SetTLSConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetTLSConfigRequest) ProtoMessage()    {}
func (*SetTLSConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{8}
}
func (m *SetTLSConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTLSConfigRequest.Unmarshal(m, b)
}
func (m *SetTLSConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTLSConfigRequest.Marshal(b, m, deterministic)
}
func (dst *SetTLSConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTLSConfigRequest.Merge(dst, src)
}
func (m *SetTLSConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetTLSConfigRequest.Size(m)
}
func (m *SetTLSConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTLSConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTLSConfigRequest proto.InternalMessageInfo

func (m *SetTLSConfigRequest) GetCafile() string {
	if m != nil {
		return m.Cafile
	}
	return ""
}

func (m *SetTLSConfigRequest) GetCertfile() string {
	if m != nil {
		return m.Certfile
	}
	return ""
}

func (m *SetTLSConfigRequest) GetKeyfile() string {
	if m != nil {
		return m.Keyfile
	}
	return ""
}

type SetTLSConfigResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTLSConfigResponse) Reset()         { *m = SetTLSConfigResponse{} }
func (m *SetTLSConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetTLSConfigResponse) ProtoMessage()    {}
func (*SetTLSConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{9}
}
func (m *SetTLSConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTLSConfigResponse.Unmarshal(m, b)
}
func (m *SetTLSConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTLSConfigResponse.Marshal(b, m, deterministic)
}
func (dst *SetTLSConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTLSConfigResponse.Merge(dst, src)
}
func (m *SetTLSConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetTLSConfigResponse.Size(m)
}
func (m *SetTLSConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTLSConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTLSConfigResponse proto.InternalMessageInfo

func (m *SetTLSConfigResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ModifyUserPwRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserPwRequest) Reset()         { *m = ModifyUserPwRequest{} }
func (m *ModifyUserPwRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyUserPwRequest) ProtoMessage()    {}
func (*ModifyUserPwRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{10}
}
func (m *ModifyUserPwRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserPwRequest.Unmarshal(m, b)
}
func (m *ModifyUserPwRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserPwRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyUserPwRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserPwRequest.Merge(dst, src)
}
func (m *ModifyUserPwRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyUserPwRequest.Size(m)
}
func (m *ModifyUserPwRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserPwRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserPwRequest proto.InternalMessageInfo

func (m *ModifyUserPwRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ModifyUserPwRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ModifyUserPwResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserPwResponse) Reset()         { *m = ModifyUserPwResponse{} }
func (m *ModifyUserPwResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyUserPwResponse) ProtoMessage()    {}
func (*ModifyUserPwResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{11}
}
func (m *ModifyUserPwResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserPwResponse.Unmarshal(m, b)
}
func (m *ModifyUserPwResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserPwResponse.Marshal(b, m, deterministic)
}
func (dst *ModifyUserPwResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserPwResponse.Merge(dst, src)
}
func (m *ModifyUserPwResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyUserPwResponse.Size(m)
}
func (m *ModifyUserPwResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserPwResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserPwResponse proto.InternalMessageInfo

func (m *ModifyUserPwResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DevStruct struct {
	Devid                string            `protobuf:"bytes,1,opt,name=devid,proto3" json:"devid,omitempty"`
	Devtype              string            `protobuf:"bytes,2,opt,name=devtype,proto3" json:"devtype,omitempty"`
	Conn                 map[string]string `protobuf:"bytes,3,rep,name=conn,proto3" json:"conn,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DevStruct) Reset()         { *m = DevStruct{} }
func (m *DevStruct) String() string { return proto.CompactTextString(m) }
func (*DevStruct) ProtoMessage()    {}
func (*DevStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{12}
}
func (m *DevStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevStruct.Unmarshal(m, b)
}
func (m *DevStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevStruct.Marshal(b, m, deterministic)
}
func (dst *DevStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevStruct.Merge(dst, src)
}
func (m *DevStruct) XXX_Size() int {
	return xxx_messageInfo_DevStruct.Size(m)
}
func (m *DevStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_DevStruct.DiscardUnknown(m)
}

var xxx_messageInfo_DevStruct proto.InternalMessageInfo

func (m *DevStruct) GetDevid() string {
	if m != nil {
		return m.Devid
	}
	return ""
}

func (m *DevStruct) GetDevtype() string {
	if m != nil {
		return m.Devtype
	}
	return ""
}

func (m *DevStruct) GetConn() map[string]string {
	if m != nil {
		return m.Conn
	}
	return nil
}

type GetDevListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDevListRequest) Reset()         { *m = GetDevListRequest{} }
func (m *GetDevListRequest) String() string { return proto.CompactTextString(m) }
func (*GetDevListRequest) ProtoMessage()    {}
func (*GetDevListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{13}
}
func (m *GetDevListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevListRequest.Unmarshal(m, b)
}
func (m *GetDevListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevListRequest.Marshal(b, m, deterministic)
}
func (dst *GetDevListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevListRequest.Merge(dst, src)
}
func (m *GetDevListRequest) XXX_Size() int {
	return xxx_messageInfo_GetDevListRequest.Size(m)
}
func (m *GetDevListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevListRequest proto.InternalMessageInfo

type GetDevListResponse struct {
	Data                 []*DevStruct `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetDevListResponse) Reset()         { *m = GetDevListResponse{} }
func (m *GetDevListResponse) String() string { return proto.CompactTextString(m) }
func (*GetDevListResponse) ProtoMessage()    {}
func (*GetDevListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{14}
}
func (m *GetDevListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevListResponse.Unmarshal(m, b)
}
func (m *GetDevListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevListResponse.Marshal(b, m, deterministic)
}
func (dst *GetDevListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevListResponse.Merge(dst, src)
}
func (m *GetDevListResponse) XXX_Size() int {
	return xxx_messageInfo_GetDevListResponse.Size(m)
}
func (m *GetDevListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevListResponse proto.InternalMessageInfo

func (m *GetDevListResponse) GetData() []*DevStruct {
	if m != nil {
		return m.Data
	}
	return nil
}

type DelDevRequest struct {
	Devid                string   `protobuf:"bytes,1,opt,name=devid,proto3" json:"devid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelDevRequest) Reset()         { *m = DelDevRequest{} }
func (m *DelDevRequest) String() string { return proto.CompactTextString(m) }
func (*DelDevRequest) ProtoMessage()    {}
func (*DelDevRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{15}
}
func (m *DelDevRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelDevRequest.Unmarshal(m, b)
}
func (m *DelDevRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelDevRequest.Marshal(b, m, deterministic)
}
func (dst *DelDevRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelDevRequest.Merge(dst, src)
}
func (m *DelDevRequest) XXX_Size() int {
	return xxx_messageInfo_DelDevRequest.Size(m)
}
func (m *DelDevRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelDevRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelDevRequest proto.InternalMessageInfo

func (m *DelDevRequest) GetDevid() string {
	if m != nil {
		return m.Devid
	}
	return ""
}

type DelDevResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelDevResponse) Reset()         { *m = DelDevResponse{} }
func (m *DelDevResponse) String() string { return proto.CompactTextString(m) }
func (*DelDevResponse) ProtoMessage()    {}
func (*DelDevResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{16}
}
func (m *DelDevResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelDevResponse.Unmarshal(m, b)
}
func (m *DelDevResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelDevResponse.Marshal(b, m, deterministic)
}
func (dst *DelDevResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelDevResponse.Merge(dst, src)
}
func (m *DelDevResponse) XXX_Size() int {
	return xxx_messageInfo_DelDevResponse.Size(m)
}
func (m *DelDevResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelDevResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelDevResponse proto.InternalMessageInfo

func (m *DelDevResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type UpdateGatewaySystemRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGatewaySystemRequest) Reset()         { *m = UpdateGatewaySystemRequest{} }
func (m *UpdateGatewaySystemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGatewaySystemRequest) ProtoMessage()    {}
func (*UpdateGatewaySystemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{17}
}
func (m *UpdateGatewaySystemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGatewaySystemRequest.Unmarshal(m, b)
}
func (m *UpdateGatewaySystemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGatewaySystemRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateGatewaySystemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGatewaySystemRequest.Merge(dst, src)
}
func (m *UpdateGatewaySystemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGatewaySystemRequest.Size(m)
}
func (m *UpdateGatewaySystemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGatewaySystemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGatewaySystemRequest proto.InternalMessageInfo

func (m *UpdateGatewaySystemRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UpdateGatewaySystemResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGatewaySystemResponse) Reset()         { *m = UpdateGatewaySystemResponse{} }
func (m *UpdateGatewaySystemResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGatewaySystemResponse) ProtoMessage()    {}
func (*UpdateGatewaySystemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{18}
}
func (m *UpdateGatewaySystemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGatewaySystemResponse.Unmarshal(m, b)
}
func (m *UpdateGatewaySystemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGatewaySystemResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateGatewaySystemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGatewaySystemResponse.Merge(dst, src)
}
func (m *UpdateGatewaySystemResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGatewaySystemResponse.Size(m)
}
func (m *UpdateGatewaySystemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGatewaySystemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGatewaySystemResponse proto.InternalMessageInfo

func (m *UpdateGatewaySystemResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DoGetValueRequest struct {
	Devid                string   `protobuf:"bytes,1,opt,name=devid,proto3" json:"devid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoGetValueRequest) Reset()         { *m = DoGetValueRequest{} }
func (m *DoGetValueRequest) String() string { return proto.CompactTextString(m) }
func (*DoGetValueRequest) ProtoMessage()    {}
func (*DoGetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{19}
}
func (m *DoGetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoGetValueRequest.Unmarshal(m, b)
}
func (m *DoGetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoGetValueRequest.Marshal(b, m, deterministic)
}
func (dst *DoGetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoGetValueRequest.Merge(dst, src)
}
func (m *DoGetValueRequest) XXX_Size() int {
	return xxx_messageInfo_DoGetValueRequest.Size(m)
}
func (m *DoGetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoGetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoGetValueRequest proto.InternalMessageInfo

func (m *DoGetValueRequest) GetDevid() string {
	if m != nil {
		return m.Devid
	}
	return ""
}

type DoGetValueResponse struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DoGetValueResponse) Reset()         { *m = DoGetValueResponse{} }
func (m *DoGetValueResponse) String() string { return proto.CompactTextString(m) }
func (*DoGetValueResponse) ProtoMessage()    {}
func (*DoGetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{20}
}
func (m *DoGetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoGetValueResponse.Unmarshal(m, b)
}
func (m *DoGetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoGetValueResponse.Marshal(b, m, deterministic)
}
func (dst *DoGetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoGetValueResponse.Merge(dst, src)
}
func (m *DoGetValueResponse) XXX_Size() int {
	return xxx_messageInfo_DoGetValueResponse.Size(m)
}
func (m *DoGetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoGetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoGetValueResponse proto.InternalMessageInfo

func (m *DoGetValueResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type DoGetHistoryRequest struct {
	Devid                string   `protobuf:"bytes,1,opt,name=devid,proto3" json:"devid,omitempty"`
	Cmdtype              string   `protobuf:"bytes,2,opt,name=cmdtype,proto3" json:"cmdtype,omitempty"`
	Since                string   `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	Until                string   `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoGetHistoryRequest) Reset()         { *m = DoGetHistoryRequest{} }
func (m *DoGetHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*DoGetHistoryRequest) ProtoMessage()    {}
func (*DoGetHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{21}
}
func (m *DoGetHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoGetHistoryRequest.Unmarshal(m, b)
}
func (m *DoGetHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoGetHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *DoGetHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoGetHistoryRequest.Merge(dst, src)
}
func (m *DoGetHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_DoGetHistoryRequest.Size(m)
}
func (m *DoGetHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoGetHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoGetHistoryRequest proto.InternalMessageInfo

func (m *DoGetHistoryRequest) GetDevid() string {
	if m != nil {
		return m.Devid
	}
	return ""
}

func (m *DoGetHistoryRequest) GetCmdtype() string {
	if m != nil {
		return m.Cmdtype
	}
	return ""
}

func (m *DoGetHistoryRequest) GetSince() string {
	if m != nil {
		return m.Since
	}
	return ""
}

func (m *DoGetHistoryRequest) GetUntil() string {
	if m != nil {
		return m.Until
	}
	return ""
}

type HistoryStuct struct {
	Cmdtype              string            `protobuf:"bytes,1,opt,name=cmdtype,proto3" json:"cmdtype,omitempty"`
	Timestamp            string            `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                map[string]string `protobuf:"bytes,3,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HistoryStuct) Reset()         { *m = HistoryStuct{} }
func (m *HistoryStuct) String() string { return proto.CompactTextString(m) }
func (*HistoryStuct) ProtoMessage()    {}
func (*HistoryStuct) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{22}
}
func (m *HistoryStuct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryStuct.Unmarshal(m, b)
}
func (m *HistoryStuct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryStuct.Marshal(b, m, deterministic)
}
func (dst *HistoryStuct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryStuct.Merge(dst, src)
}
func (m *HistoryStuct) XXX_Size() int {
	return xxx_messageInfo_HistoryStuct.Size(m)
}
func (m *HistoryStuct) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryStuct.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryStuct proto.InternalMessageInfo

func (m *HistoryStuct) GetCmdtype() string {
	if m != nil {
		return m.Cmdtype
	}
	return ""
}

func (m *HistoryStuct) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *HistoryStuct) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

type DoGetHistoryResponse struct {
	Data                 []*HistoryStuct `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DoGetHistoryResponse) Reset()         { *m = DoGetHistoryResponse{} }
func (m *DoGetHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*DoGetHistoryResponse) ProtoMessage()    {}
func (*DoGetHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_4fd6f9542ab344df, []int{23}
}
func (m *DoGetHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoGetHistoryResponse.Unmarshal(m, b)
}
func (m *DoGetHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoGetHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *DoGetHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoGetHistoryResponse.Merge(dst, src)
}
func (m *DoGetHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_DoGetHistoryResponse.Size(m)
}
func (m *DoGetHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoGetHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoGetHistoryResponse proto.InternalMessageInfo

func (m *DoGetHistoryResponse) GetData() []*HistoryStuct {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SetGatewayManageRequest)(nil), "api.SetGatewayManageRequest")
	proto.RegisterType((*SetGatewayManageResponse)(nil), "api.SetGatewayManageResponse")
	proto.RegisterType((*GetGatewayManageResponse)(nil), "api.GetGatewayManageResponse")
	proto.RegisterType((*GetGatewayManageRequest)(nil), "api.GetGatewayManageRequest")
	proto.RegisterType((*GetSuppotRequest)(nil), "api.GetSuppotRequest")
	proto.RegisterType((*GetSuppotResponse)(nil), "api.GetSuppotResponse")
	proto.RegisterType((*SetIntervalRequest)(nil), "api.SetIntervalRequest")
	proto.RegisterType((*SetIntervalResponse)(nil), "api.SetIntervalResponse")
	proto.RegisterType((*SetTLSConfigRequest)(nil), "api.SetTLSConfigRequest")
	proto.RegisterType((*SetTLSConfigResponse)(nil), "api.SetTLSConfigResponse")
	proto.RegisterType((*ModifyUserPwRequest)(nil), "api.ModifyUserPwRequest")
	proto.RegisterType((*ModifyUserPwResponse)(nil), "api.ModifyUserPwResponse")
	proto.RegisterType((*DevStruct)(nil), "api.DevStruct")
	proto.RegisterMapType((map[string]string)(nil), "api.DevStruct.ConnEntry")
	proto.RegisterType((*GetDevListRequest)(nil), "api.GetDevListRequest")
	proto.RegisterType((*GetDevListResponse)(nil), "api.GetDevListResponse")
	proto.RegisterType((*DelDevRequest)(nil), "api.DelDevRequest")
	proto.RegisterType((*DelDevResponse)(nil), "api.DelDevResponse")
	proto.RegisterType((*UpdateGatewaySystemRequest)(nil), "api.UpdateGatewaySystemRequest")
	proto.RegisterType((*UpdateGatewaySystemResponse)(nil), "api.UpdateGatewaySystemResponse")
	proto.RegisterType((*DoGetValueRequest)(nil), "api.DoGetValueRequest")
	proto.RegisterType((*DoGetValueResponse)(nil), "api.DoGetValueResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.DoGetValueResponse.DataEntry")
	proto.RegisterType((*DoGetHistoryRequest)(nil), "api.DoGetHistoryRequest")
	proto.RegisterType((*HistoryStuct)(nil), "api.HistoryStuct")
	proto.RegisterMapType((map[string]string)(nil), "api.HistoryStuct.ValueEntry")
	proto.RegisterType((*DoGetHistoryResponse)(nil), "api.DoGetHistoryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayServiceClient interface {
	// 设置网关配置参数
	GatewaySet(ctx context.Context, in *SetGatewayManageRequest, opts ...grpc.CallOption) (*SetGatewayManageResponse, error)
	// 查看网关当前的配置
	GatewayGet(ctx context.Context, in *GetGatewayManageRequest, opts ...grpc.CallOption) (*GetGatewayManageResponse, error)
	// 查看网关支持的设备列表
	SuppotList(ctx context.Context, in *GetSuppotRequest, opts ...grpc.CallOption) (*GetSuppotResponse, error)
	// 设置网关自动上报的时间间隔(0为不自动上报)
	SetInterval(ctx context.Context, in *SetIntervalRequest, opts ...grpc.CallOption) (*SetIntervalResponse, error)
	// 设置网关SSL/TLS(http://xxx.xxx.xxx/...)
	SetTLSConfig(ctx context.Context, in *SetTLSConfigRequest, opts ...grpc.CallOption) (*SetTLSConfigResponse, error)
	// 修改用户名和密码
	ModifyUserPw(ctx context.Context, in *ModifyUserPwRequest, opts ...grpc.CallOption) (*ModifyUserPwResponse, error)
	// 查看已添加的设备列表
	DevList(ctx context.Context, in *GetDevListRequest, opts ...grpc.CallOption) (*GetDevListResponse, error)
	// 删除设备
	DevDelete(ctx context.Context, in *DelDevRequest, opts ...grpc.CallOption) (*DelDevResponse, error)
	// 更新网关系统(http://xxx.xxx.xxx/...)
	UpdateGatewaySystem(ctx context.Context, in *UpdateGatewaySystemRequest, opts ...grpc.CallOption) (*UpdateGatewaySystemResponse, error)
	// 读取设备当前的值
	DoGetValue(ctx context.Context, in *DoGetValueRequest, opts ...grpc.CallOption) (*DoGetValueResponse, error)
	// 读设备历史记录
	DoGetHistory(ctx context.Context, in *DoGetHistoryRequest, opts ...grpc.CallOption) (*DoGetHistoryResponse, error)
}

type gatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayServiceClient(cc *grpc.ClientConn) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GatewaySet(ctx context.Context, in *SetGatewayManageRequest, opts ...grpc.CallOption) (*SetGatewayManageResponse, error) {
	out := new(SetGatewayManageResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/GatewaySet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GatewayGet(ctx context.Context, in *GetGatewayManageRequest, opts ...grpc.CallOption) (*GetGatewayManageResponse, error) {
	out := new(GetGatewayManageResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/GatewayGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SuppotList(ctx context.Context, in *GetSuppotRequest, opts ...grpc.CallOption) (*GetSuppotResponse, error) {
	out := new(GetSuppotResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/SuppotList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SetInterval(ctx context.Context, in *SetIntervalRequest, opts ...grpc.CallOption) (*SetIntervalResponse, error) {
	out := new(SetIntervalResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/SetInterval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SetTLSConfig(ctx context.Context, in *SetTLSConfigRequest, opts ...grpc.CallOption) (*SetTLSConfigResponse, error) {
	out := new(SetTLSConfigResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/SetTLSConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ModifyUserPw(ctx context.Context, in *ModifyUserPwRequest, opts ...grpc.CallOption) (*ModifyUserPwResponse, error) {
	out := new(ModifyUserPwResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/ModifyUserPw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DevList(ctx context.Context, in *GetDevListRequest, opts ...grpc.CallOption) (*GetDevListResponse, error) {
	out := new(GetDevListResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/DevList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DevDelete(ctx context.Context, in *DelDevRequest, opts ...grpc.CallOption) (*DelDevResponse, error) {
	out := new(DelDevResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/DevDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) UpdateGatewaySystem(ctx context.Context, in *UpdateGatewaySystemRequest, opts ...grpc.CallOption) (*UpdateGatewaySystemResponse, error) {
	out := new(UpdateGatewaySystemResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/UpdateGatewaySystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DoGetValue(ctx context.Context, in *DoGetValueRequest, opts ...grpc.CallOption) (*DoGetValueResponse, error) {
	out := new(DoGetValueResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/DoGetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DoGetHistory(ctx context.Context, in *DoGetHistoryRequest, opts ...grpc.CallOption) (*DoGetHistoryResponse, error) {
	out := new(DoGetHistoryResponse)
	err := c.cc.Invoke(ctx, "/api.GatewayService/DoGetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
type GatewayServiceServer interface {
	// 设置网关配置参数
	GatewaySet(context.Context, *SetGatewayManageRequest) (*SetGatewayManageResponse, error)
	// 查看网关当前的配置
	GatewayGet(context.Context, *GetGatewayManageRequest) (*GetGatewayManageResponse, error)
	// 查看网关支持的设备列表
	SuppotList(context.Context, *GetSuppotRequest) (*GetSuppotResponse, error)
	// 设置网关自动上报的时间间隔(0为不自动上报)
	SetInterval(context.Context, *SetIntervalRequest) (*SetIntervalResponse, error)
	// 设置网关SSL/TLS(http://xxx.xxx.xxx/...)
	SetTLSConfig(context.Context, *SetTLSConfigRequest) (*SetTLSConfigResponse, error)
	// 修改用户名和密码
	ModifyUserPw(context.Context, *ModifyUserPwRequest) (*ModifyUserPwResponse, error)
	// 查看已添加的设备列表
	DevList(context.Context, *GetDevListRequest) (*GetDevListResponse, error)
	// 删除设备
	DevDelete(context.Context, *DelDevRequest) (*DelDevResponse, error)
	// 更新网关系统(http://xxx.xxx.xxx/...)
	UpdateGatewaySystem(context.Context, *UpdateGatewaySystemRequest) (*UpdateGatewaySystemResponse, error)
	// 读取设备当前的值
	DoGetValue(context.Context, *DoGetValueRequest) (*DoGetValueResponse, error)
	// 读设备历史记录
	DoGetHistory(context.Context, *DoGetHistoryRequest) (*DoGetHistoryResponse, error)
}

func RegisterGatewayServiceServer(s *grpc.Server, srv GatewayServiceServer) {
	s.RegisterService(&_GatewayService_serviceDesc, srv)
}

func _GatewayService_GatewaySet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGatewayManageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GatewaySet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/GatewaySet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GatewaySet(ctx, req.(*SetGatewayManageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GatewayGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayManageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GatewayGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/GatewayGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GatewayGet(ctx, req.(*GetGatewayManageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SuppotList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuppotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SuppotList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/SuppotList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SuppotList(ctx, req.(*GetSuppotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SetInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIntervalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SetInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/SetInterval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SetInterval(ctx, req.(*SetIntervalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SetTLSConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTLSConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SetTLSConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/SetTLSConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SetTLSConfig(ctx, req.(*SetTLSConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ModifyUserPw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUserPwRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ModifyUserPw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/ModifyUserPw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ModifyUserPw(ctx, req.(*ModifyUserPwRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DevList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DevList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/DevList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DevList(ctx, req.(*GetDevListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DevDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelDevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DevDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/DevDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DevDelete(ctx, req.(*DelDevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_UpdateGatewaySystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewaySystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).UpdateGatewaySystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/UpdateGatewaySystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).UpdateGatewaySystem(ctx, req.(*UpdateGatewaySystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DoGetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoGetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DoGetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/DoGetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DoGetValue(ctx, req.(*DoGetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DoGetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoGetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DoGetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GatewayService/DoGetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DoGetHistory(ctx, req.(*DoGetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GatewaySet",
			Handler:    _GatewayService_GatewaySet_Handler,
		},
		{
			MethodName: "GatewayGet",
			Handler:    _GatewayService_GatewayGet_Handler,
		},
		{
			MethodName: "SuppotList",
			Handler:    _GatewayService_SuppotList_Handler,
		},
		{
			MethodName: "SetInterval",
			Handler:    _GatewayService_SetInterval_Handler,
		},
		{
			MethodName: "SetTLSConfig",
			Handler:    _GatewayService_SetTLSConfig_Handler,
		},
		{
			MethodName: "ModifyUserPw",
			Handler:    _GatewayService_ModifyUserPw_Handler,
		},
		{
			MethodName: "DevList",
			Handler:    _GatewayService_DevList_Handler,
		},
		{
			MethodName: "DevDelete",
			Handler:    _GatewayService_DevDelete_Handler,
		},
		{
			MethodName: "UpdateGatewaySystem",
			Handler:    _GatewayService_UpdateGatewaySystem_Handler,
		},
		{
			MethodName: "DoGetValue",
			Handler:    _GatewayService_DoGetValue_Handler,
		},
		{
			MethodName: "DoGetHistory",
			Handler:    _GatewayService_DoGetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_gateway_4fd6f9542ab344df) }

var fileDescriptor_gateway_4fd6f9542ab344df = []byte{
	// 1167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x96, 0xe3, 0xfc, 0xac, 0xcb, 0x4e, 0x94, 0xb4, 0x43, 0x3c, 0x19, 0x92, 0x8d, 0x19, 0x29,
	0x52, 0x58, 0x81, 0x83, 0x82, 0x22, 0xa2, 0x95, 0x38, 0xad, 0x91, 0x89, 0xb4, 0x41, 0x51, 0xcc,
	0x22, 0x2e, 0xc8, 0x6a, 0x66, 0x2a, 0xde, 0x21, 0xe3, 0x99, 0xc9, 0x74, 0x8f, 0x23, 0x0b, 0x21,
	0x24, 0xc4, 0x9d, 0x03, 0x4f, 0x00, 0x27, 0x1e, 0x80, 0x37, 0xe1, 0x15, 0x78, 0x10, 0xd4, 0x7f,
	0xe3, 0x1e, 0xff, 0x24, 0xda, 0x23, 0x37, 0x57, 0x75, 0x75, 0x7d, 0x5d, 0x5f, 0x7f, 0x5d, 0x35,
	0x86, 0xcd, 0x21, 0xe5, 0xf8, 0x40, 0x27, 0x9d, 0x34, 0x4b, 0x78, 0x42, 0xaa, 0x34, 0x0d, 0xdd,
	0x83, 0x61, 0x92, 0x0c, 0x23, 0x3c, 0xa5, 0x69, 0x78, 0x4a, 0xe3, 0x38, 0xe1, 0x94, 0x87, 0x49,
	0xcc, 0x54, 0x88, 0xf7, 0xc7, 0x0a, 0xb4, 0xfa, 0xc8, 0x7b, 0x6a, 0xdf, 0x15, 0x8d, 0xe9, 0x10,
	0x6f, 0xf0, 0x3e, 0x47, 0xc6, 0x89, 0x0b, 0xcf, 0xfc, 0x28, 0xc4, 0x98, 0x5f, 0xa6, 0xce, 0x4a,
	0xbb, 0x72, 0x52, 0xbb, 0x29, 0x6c, 0x42, 0x60, 0x35, 0x8c, 0x91, 0x3b, 0xcf, 0xa4, 0x5f, 0xfe,
	0x26, 0x0e, 0x6c, 0xc4, 0xc8, 0x47, 0x94, 0xdd, 0x39, 0x35, 0xe9, 0x36, 0xa6, 0x58, 0xd1, 0x27,
	0x73, 0x40, 0xad, 0x68, 0x53, 0x60, 0x30, 0xcc, 0xc6, 0x98, 0x5d, 0xa6, 0x4e, 0x55, 0x61, 0x18,
	0x9b, 0x3c, 0x07, 0x50, 0xbf, 0xbf, 0xa2, 0x23, 0x74, 0x56, 0xe5, 0xaa, 0xe5, 0x99, 0xae, 0x5f,
	0x27, 0x19, 0x77, 0xd6, 0xec, 0x75, 0xe1, 0x21, 0x1e, 0x34, 0x46, 0xf7, 0x9c, 0xbf, 0x61, 0x98,
	0xc5, 0x22, 0xc3, 0xba, 0x8c, 0x28, 0xf9, 0x4c, 0xcc, 0x35, 0x65, 0xec, 0x21, 0xc9, 0x02, 0x67,
	0x63, 0x1a, 0x63, 0x7c, 0xde, 0x19, 0x38, 0xf3, 0x14, 0xb1, 0x34, 0x89, 0x19, 0x92, 0x3d, 0x58,
	0xcf, 0x90, 0xe5, 0x11, 0x77, 0x2a, 0x72, 0xa7, 0xb6, 0xbc, 0xbf, 0xaa, 0xe0, 0xf4, 0x96, 0x6d,
	0x9a, 0x12, 0x1b, 0xe8, 0x6d, 0x85, 0xfd, 0x28, 0xe9, 0x16, 0xc1, 0xb0, 0x94, 0xe0, 0xfa, 0xff,
	0x8e, 0x60, 0x71, 0xc6, 0x30, 0xe6, 0x98, 0x8d, 0x69, 0xa4, 0x05, 0x55, 0xd8, 0xe2, 0x0c, 0x22,
	0xb6, 0xcf, 0x29, 0xcf, 0x99, 0xd6, 0x95, 0xe5, 0x21, 0x6d, 0xa8, 0xbf, 0x0d, 0x19, 0x4f, 0xb2,
	0x49, 0x40, 0x27, 0xcc, 0x69, 0xc8, 0x00, 0xdb, 0x25, 0xab, 0x98, 0x30, 0x8e, 0x23, 0xb1, 0xc3,
	0xd9, 0xd4, 0x55, 0x14, 0x1e, 0x6f, 0x1f, 0x5a, 0xbd, 0xc5, 0x2f, 0xc0, 0x23, 0xb0, 0xdd, 0x43,
	0xde, 0xcf, 0xd3, 0x34, 0xe1, 0xc6, 0x77, 0x0e, 0x3b, 0x96, 0x4f, 0xdf, 0x68, 0x1b, 0xea, 0x4c,
	0x78, 0x32, 0x1e, 0x85, 0x4c, 0x68, 0xa1, 0x2a, 0x4e, 0x61, 0xb9, 0xbc, 0x4f, 0x80, 0xf4, 0x91,
	0x5f, 0xea, 0xb2, 0xac, 0x27, 0x56, 0x54, 0x2e, 0x94, 0xb0, 0x36, 0xad, 0xdc, 0xfb, 0x18, 0x9a,
	0xa5, 0x1d, 0x4f, 0x28, 0xce, 0x97, 0xe1, 0x5f, 0xbf, 0xee, 0xbf, 0x4a, 0xe2, 0xdb, 0x70, 0x68,
	0x10, 0xf6, 0x60, 0xdd, 0xa7, 0xb7, 0x61, 0x84, 0x26, 0x5c, 0x59, 0x52, 0x67, 0x98, 0x71, 0xb9,
	0x62, 0x74, 0xa6, 0x6d, 0xa1, 0xa6, 0x3b, 0x9c, 0xc8, 0x25, 0x25, 0x19, 0x63, 0x7a, 0x1d, 0xd8,
	0x2d, 0x83, 0x3c, 0x71, 0xa8, 0x2b, 0x68, 0x5e, 0x25, 0x41, 0x78, 0x3b, 0x11, 0x7a, 0xb8, 0x7e,
	0xb0, 0xca, 0xce, 0x8d, 0x68, 0xf4, 0x03, 0x30, 0xb6, 0x58, 0x4b, 0x8d, 0x58, 0xf4, 0xc1, 0x8c,
	0x2d, 0xe0, 0xcb, 0xe9, 0x9e, 0x80, 0xff, 0xb3, 0x02, 0xb5, 0x2e, 0x8e, 0xfb, 0x3c, 0xcb, 0x7d,
	0x4e, 0x76, 0x61, 0x2d, 0xc0, 0x71, 0x68, 0xde, 0x9c, 0x32, 0x44, 0xb1, 0x01, 0x8e, 0xf9, 0x24,
	0x35, 0x3c, 0x18, 0x93, 0x7c, 0x04, 0xab, 0x7e, 0x12, 0xc7, 0x4e, 0xb5, 0x5d, 0x3d, 0xa9, 0x9f,
	0x39, 0x1d, 0x9a, 0x86, 0x9d, 0x22, 0x5b, 0xe7, 0x55, 0x12, 0xc7, 0x5f, 0xc4, 0x3c, 0x9b, 0xdc,
	0xc8, 0x28, 0xf7, 0x33, 0xa8, 0x15, 0x2e, 0xb2, 0x0d, 0xd5, 0x3b, 0x9c, 0x68, 0x20, 0xf1, 0x53,
	0x80, 0x8f, 0x69, 0x94, 0x1b, 0x10, 0x65, 0xbc, 0x5c, 0xb9, 0xa8, 0x78, 0x4d, 0x29, 0xa8, 0x2e,
	0x8e, 0x5f, 0x87, 0xac, 0x50, 0xd9, 0x05, 0x10, 0xdb, 0xa9, 0xeb, 0xf4, 0x60, 0x35, 0xa0, 0x9c,
	0x4a, 0x7d, 0xd5, 0xcf, 0xb6, 0xca, 0x27, 0xba, 0x91, 0x6b, 0xde, 0x31, 0x6c, 0x76, 0x31, 0xea,
	0xe2, 0xd8, 0x90, 0xbd, 0xb0, 0x6c, 0xef, 0x04, 0xb6, 0x4c, 0xd8, 0x13, 0x24, 0x76, 0xc0, 0x7d,
	0x93, 0x06, 0x94, 0xa3, 0x7e, 0x22, 0x7d, 0xf9, 0x74, 0x4c, 0xf6, 0x6d, 0xa8, 0xe6, 0x59, 0x64,
	0x2a, 0xcd, 0xb3, 0xc8, 0x3b, 0x87, 0xf7, 0x17, 0xc6, 0x3f, 0x01, 0xf3, 0x21, 0xec, 0x74, 0x93,
	0x1e, 0xf2, 0x6f, 0x04, 0x31, 0x8f, 0x9f, 0xfd, 0xd7, 0x0a, 0x10, 0x3b, 0x56, 0x67, 0x3e, 0x2f,
	0xb1, 0xf3, 0x81, 0x62, 0x67, 0x2e, 0xac, 0xd3, 0xa5, 0x9c, 0xea, 0x8b, 0x13, 0xe1, 0xe2, 0xe2,
	0x0a, 0xd7, 0x3b, 0x5d, 0xdc, 0x3d, 0x34, 0x65, 0xfa, 0x2f, 0x55, 0xb3, 0x79, 0xf4, 0xcc, 0x42,
	0x66, 0xfe, 0x28, 0xb0, 0x65, 0xa6, 0x4d, 0x11, 0xcf, 0xc2, 0xd8, 0x37, 0x6f, 0x4d, 0x19, 0xc2,
	0x9b, 0xc7, 0x3c, 0x8c, 0x74, 0x5b, 0x56, 0x86, 0xf7, 0x77, 0x05, 0x1a, 0x1a, 0xae, 0xcf, 0x85,
	0xa6, 0xad, 0xb4, 0x95, 0x72, 0xda, 0x03, 0xa8, 0xf1, 0x70, 0x84, 0x8c, 0xd3, 0x91, 0x99, 0x24,
	0x53, 0x07, 0x39, 0x33, 0x55, 0x29, 0x71, 0x1f, 0x48, 0xb2, 0xec, 0xcc, 0x1d, 0x49, 0x9a, 0xe2,
	0x49, 0x85, 0xba, 0x17, 0x00, 0x53, 0xe7, 0x3b, 0x31, 0xf5, 0x39, 0xec, 0x96, 0x99, 0xd2, 0x37,
	0x76, 0x5c, 0xba, 0xb1, 0x9d, 0xb9, 0x43, 0xa8, 0x1b, 0x3a, 0xfb, 0xad, 0x06, 0x5b, 0x46, 0x4c,
	0x98, 0x8d, 0x43, 0x1f, 0xc9, 0x08, 0xa0, 0xf0, 0x70, 0xa2, 0x8e, 0xbf, 0xe4, 0x3b, 0xc6, 0x3d,
	0x5c, 0xb2, 0xaa, 0x0e, 0xe1, 0x79, 0xbf, 0xfc, 0xf3, 0xef, 0xef, 0x2b, 0x07, 0x6e, 0x4b, 0x7e,
	0x22, 0x31, 0xe4, 0x03, 0x3d, 0x3b, 0x07, 0xbe, 0x6c, 0x72, 0x2f, 0x2b, 0x2f, 0xc8, 0x5d, 0x01,
	0xd7, 0x2b, 0xe0, 0x7a, 0x8f, 0xc2, 0x2d, 0x1b, 0xfe, 0x5e, 0x5b, 0xc2, 0xb9, 0xc4, 0x51, 0x70,
	0x6f, 0x93, 0x87, 0x19, 0x3c, 0xf2, 0x1d, 0x80, 0x1a, 0x2f, 0xe2, 0xed, 0x93, 0xf7, 0x4c, 0xba,
	0xd2, 0x18, 0x72, 0xf7, 0x66, 0xdd, 0x0b, 0xd3, 0x8b, 0xd1, 0x33, 0xd0, 0x63, 0x68, 0x20, 0x84,
	0xe8, 0x23, 0xf9, 0x01, 0xea, 0xd6, 0x5c, 0x21, 0x2d, 0xc3, 0xce, 0xcc, 0x6c, 0x72, 0x9d, 0xf9,
	0x05, 0x8d, 0x71, 0x22, 0x31, 0x3c, 0xf7, 0xb0, 0x60, 0x8c, 0xe6, 0x3c, 0x19, 0xe4, 0xe2, 0xd5,
	0xd3, 0x81, 0x19, 0x60, 0x82, 0x37, 0x1f, 0x1a, 0xf6, 0xbc, 0x20, 0x45, 0xce, 0xd9, 0x39, 0xe5,
	0xee, 0x2f, 0x58, 0xd1, 0x70, 0xcf, 0x25, 0x9c, 0xe3, 0x36, 0x0b, 0x38, 0x1e, 0x31, 0xeb, 0x72,
	0x86, 0xd0, 0xb0, 0xa7, 0x82, 0x06, 0x59, 0x30, 0x77, 0x34, 0xc8, 0xa2, 0x11, 0x32, 0xa3, 0x82,
	0x91, 0x0c, 0x19, 0x88, 0xa1, 0x34, 0x90, 0xd3, 0x27, 0x10, 0x40, 0x14, 0x36, 0x74, 0x47, 0x26,
	0x05, 0xfd, 0xe5, 0xbe, 0xed, 0xb6, 0xe6, 0xfc, 0x3a, 0xff, 0xb1, 0xcc, 0x7f, 0x44, 0x0e, 0xa7,
	0xd7, 0xee, 0xe7, 0x59, 0x86, 0xb1, 0xb9, 0x97, 0x81, 0xb8, 0x2b, 0xf2, 0xad, 0x1c, 0x58, 0x5d,
	0x8c, 0x90, 0x23, 0x21, 0xba, 0xc1, 0x5b, 0xdd, 0xdc, 0x6d, 0x96, 0x7c, 0xe5, 0xc3, 0xbf, 0x70,
	0x65, 0xf2, 0x0c, 0x47, 0xc9, 0x18, 0x75, 0xda, 0xd3, 0x1f, 0x65, 0xff, 0xf9, 0x89, 0xfc, 0x0c,
	0xcd, 0x05, 0x6d, 0x99, 0x1c, 0xc9, 0x7c, 0xcb, 0x1b, 0xbc, 0xdb, 0x5e, 0x1e, 0x50, 0x2e, 0xcd,
	0x55, 0xe8, 0x52, 0x05, 0x58, 0x68, 0x5a, 0x7d, 0x68, 0x09, 0xf6, 0x02, 0x80, 0x69, 0x37, 0xd6,
	0x04, 0xce, 0x75, 0x7c, 0x4d, 0xe0, 0x7c, 0xdb, 0x9e, 0x21, 0x70, 0x88, 0x05, 0x6f, 0xb2, 0xcd,
	0x14, 0x65, 0x06, 0xd0, 0xb0, 0x5b, 0x8d, 0x16, 0xc3, 0x82, 0x3e, 0xad, 0xc5, 0xb0, 0xa8, 0x2f,
	0x79, 0x47, 0x12, 0x6b, 0x9f, 0xb4, 0x66, 0xb1, 0xf4, 0x77, 0xe5, 0xf7, 0xeb, 0xf2, 0xdf, 0xd3,
	0xa7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x7c, 0xd9, 0xd7, 0x71, 0x0d, 0x00, 0x00,
}
