// Code generated by protoc-gen-go. DO NOT EDIT.
// source: watermeter.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WaterMeterUpdateRequest struct {
	Devid                string   `protobuf:"bytes,1,opt,name=devid,proto3" json:"devid,omitempty"`
	Devtype              string   `protobuf:"bytes,2,opt,name=devtype,proto3" json:"devtype,omitempty"`
	Devaddr              string   `protobuf:"bytes,3,opt,name=devaddr,proto3" json:"devaddr,omitempty"`
	Commif               string   `protobuf:"bytes,4,opt,name=commif,proto3" json:"commif,omitempty"`
	Fcode                string   `protobuf:"bytes,5,opt,name=fcode,proto3" json:"fcode,omitempty"`
	Dname                string   `protobuf:"bytes,6,opt,name=dname,proto3" json:"dname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaterMeterUpdateRequest) Reset()         { *m = WaterMeterUpdateRequest{} }
func (m *WaterMeterUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*WaterMeterUpdateRequest) ProtoMessage()    {}
func (*WaterMeterUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_watermeter_3c36b2e580175fe7, []int{0}
}
func (m *WaterMeterUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterMeterUpdateRequest.Unmarshal(m, b)
}
func (m *WaterMeterUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterMeterUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *WaterMeterUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterMeterUpdateRequest.Merge(dst, src)
}
func (m *WaterMeterUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_WaterMeterUpdateRequest.Size(m)
}
func (m *WaterMeterUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterMeterUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaterMeterUpdateRequest proto.InternalMessageInfo

func (m *WaterMeterUpdateRequest) GetDevid() string {
	if m != nil {
		return m.Devid
	}
	return ""
}

func (m *WaterMeterUpdateRequest) GetDevtype() string {
	if m != nil {
		return m.Devtype
	}
	return ""
}

func (m *WaterMeterUpdateRequest) GetDevaddr() string {
	if m != nil {
		return m.Devaddr
	}
	return ""
}

func (m *WaterMeterUpdateRequest) GetCommif() string {
	if m != nil {
		return m.Commif
	}
	return ""
}

func (m *WaterMeterUpdateRequest) GetFcode() string {
	if m != nil {
		return m.Fcode
	}
	return ""
}

func (m *WaterMeterUpdateRequest) GetDname() string {
	if m != nil {
		return m.Dname
	}
	return ""
}

type WaterMeterUpdateResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaterMeterUpdateResponse) Reset()         { *m = WaterMeterUpdateResponse{} }
func (m *WaterMeterUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*WaterMeterUpdateResponse) ProtoMessage()    {}
func (*WaterMeterUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_watermeter_3c36b2e580175fe7, []int{1}
}
func (m *WaterMeterUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterMeterUpdateResponse.Unmarshal(m, b)
}
func (m *WaterMeterUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterMeterUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *WaterMeterUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterMeterUpdateResponse.Merge(dst, src)
}
func (m *WaterMeterUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_WaterMeterUpdateResponse.Size(m)
}
func (m *WaterMeterUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterMeterUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaterMeterUpdateResponse proto.InternalMessageInfo

func (m *WaterMeterUpdateResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*WaterMeterUpdateRequest)(nil), "api.WaterMeterUpdateRequest")
	proto.RegisterType((*WaterMeterUpdateResponse)(nil), "api.WaterMeterUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WaterMeterClient is the client API for WaterMeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WaterMeterClient interface {
	// 添加或更新水表设备
	WaterMeterUpdate(ctx context.Context, in *WaterMeterUpdateRequest, opts ...grpc.CallOption) (*WaterMeterUpdateResponse, error)
}

type waterMeterClient struct {
	cc *grpc.ClientConn
}

func NewWaterMeterClient(cc *grpc.ClientConn) WaterMeterClient {
	return &waterMeterClient{cc}
}

func (c *waterMeterClient) WaterMeterUpdate(ctx context.Context, in *WaterMeterUpdateRequest, opts ...grpc.CallOption) (*WaterMeterUpdateResponse, error) {
	out := new(WaterMeterUpdateResponse)
	err := c.cc.Invoke(ctx, "/api.WaterMeter/WaterMeterUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaterMeterServer is the server API for WaterMeter service.
type WaterMeterServer interface {
	// 添加或更新水表设备
	WaterMeterUpdate(context.Context, *WaterMeterUpdateRequest) (*WaterMeterUpdateResponse, error)
}

func RegisterWaterMeterServer(s *grpc.Server, srv WaterMeterServer) {
	s.RegisterService(&_WaterMeter_serviceDesc, srv)
}

func _WaterMeter_WaterMeterUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaterMeterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterMeterServer).WaterMeterUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WaterMeter/WaterMeterUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterMeterServer).WaterMeterUpdate(ctx, req.(*WaterMeterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WaterMeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WaterMeter",
	HandlerType: (*WaterMeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WaterMeterUpdate",
			Handler:    _WaterMeter_WaterMeterUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "watermeter.proto",
}

func init() { proto.RegisterFile("watermeter.proto", fileDescriptor_watermeter_3c36b2e580175fe7) }

var fileDescriptor_watermeter_3c36b2e580175fe7 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0x6b, 0x2b, 0xe6, 0x54, 0x82, 0x68, 0x58, 0xaa, 0xc8, 0x7a, 0x51, 0x0f, 0x5b,
	0xa8, 0x37, 0xdf, 0xc1, 0xcb, 0x82, 0x78, 0x5c, 0xc6, 0x66, 0x5a, 0x02, 0xdd, 0x4c, 0x4c, 0xb2,
	0x15, 0x3d, 0x7a, 0xf2, 0xee, 0x43, 0xf8, 0x40, 0xbe, 0x82, 0x0f, 0x22, 0xc9, 0x46, 0x0b, 0x4a,
	0x8f, 0xdf, 0xfc, 0xf3, 0xcf, 0x3f, 0xfc, 0x7c, 0xf2, 0x04, 0x01, 0x5d, 0x8b, 0x01, 0x5d, 0x65,
	0x1d, 0x05, 0x12, 0x43, 0xb0, 0xba, 0x98, 0xae, 0x88, 0x56, 0x6b, 0x9c, 0x81, 0xd5, 0x33, 0x30,
	0x86, 0x02, 0x04, 0x4d, 0xc6, 0xf7, 0x2b, 0xe5, 0x07, 0xe3, 0xc7, 0xf7, 0xd1, 0x77, 0x1b, 0x7d,
	0x77, 0x56, 0x41, 0xc0, 0x1a, 0x1f, 0x3b, 0xf4, 0x41, 0x1c, 0xf2, 0x91, 0xc2, 0x8d, 0x56, 0x92,
	0x9d, 0xb1, 0x8b, 0x83, 0xba, 0x07, 0x21, 0xf9, 0xbe, 0xc2, 0x4d, 0x78, 0xb6, 0x28, 0x07, 0x69,
	0xfe, 0x83, 0x59, 0x01, 0xa5, 0x9c, 0x1c, 0xfe, 0x2a, 0x11, 0xc5, 0x11, 0x1f, 0x2f, 0xa8, 0x6d,
	0xf5, 0x52, 0xee, 0x25, 0x21, 0x53, 0x4c, 0x58, 0x2e, 0x48, 0xa1, 0x1c, 0xf5, 0x09, 0x09, 0x52,
	0xae, 0x81, 0x16, 0xe5, 0x38, 0xe7, 0x46, 0x28, 0xe7, 0x5c, 0xfe, 0x7f, 0xd4, 0x5b, 0x32, 0x1e,
	0xe3, 0xfd, 0x1a, 0x7d, 0xb7, 0x0e, 0xf9, 0xd5, 0x4c, 0xf3, 0x37, 0xc6, 0xf9, 0xd6, 0x24, 0x5e,
	0xf8, 0xe4, 0xef, 0x09, 0x31, 0xad, 0xc0, 0xea, 0x6a, 0x47, 0x05, 0xc5, 0xc9, 0x0e, 0xb5, 0xcf,
	0x2d, 0x2f, 0x5f, 0x3f, 0xbf, 0xde, 0x07, 0xe7, 0xc5, 0x69, 0x6a, 0x77, 0xdb, 0x7f, 0x03, 0x4a,
	0x35, 0xe4, 0x9a, 0xce, 0xa6, 0xfd, 0x1b, 0x76, 0xf5, 0x30, 0x4e, 0x7d, 0x5f, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x89, 0xb8, 0x2f, 0xa6, 0x01, 0x00, 0x00,
}
